apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notes-app

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-deployment.yaml
  - 03-service.yaml
  - 04-hpa.yaml
  - 05-ingress.yaml

commonLabels:
  app: notes-app
  environment: production
